### ISSUE TITLE
message state lost after reconnecting state

### ISSUE THREAD

**Issue by androiddev1992** [MyPureCloud/genesys-messenger-transport-mobile-sdk#173]
After MessageInserted event if client goes into Reconnecting state, and after successful reconnection to Configured state, MessageUpdated event is not received which causes inconsistencies on client side.

From agent portal when sending a message and client is in Reconnecting state, message gets lost and not received after successful reconnection to Configured state.

After version update to 2.3.0, frequent reconnection is observed(every 3-4 seconds)

**Comment by AfanasievAnton** [comment]
Hi, @androiddev1992,

Thank you for raising this issue.

The transport dispatches the `MessageInserted` event as soon as a request to send the message is dispatched to the backend via websocket. However, it does not guarantee that the message has been delivered, unless you have received a `MessageUpdated` event with the `Message.State.Sent` status. In cases where the connection is lost, the transport cannot receive a confirmation of message delivery, and we may not know about messages that were potentially sent by the agent during the reconnection period. Therefore, you need to use the `fetchNextPage()` API when the transport is successfully configured after reconnection so that the conversation can stay in sync.

Please refer to the following documentation for more information:

https://developer.genesys.cloud/commdigital/digital/webmessaging/messenger-transport-mobile-sdk/reconnecting
https://developer.genesys.cloud/commdigital/digital/webmessaging/messenger-transport-mobile-sdk/messaging#sending-message
https://developer.genesys.cloud/commdigital/digital/webmessaging/messenger-transport-mobile-sdk/client-states#states-flow

Regarding the frequent reconnection observations, could you provide more details on the platform you are testing? Is it Android or iOS? What was the previous version of the transport that you used, which had fewer reconnection issues?

Thank you.

**Comment by androiddev1992** [comment]
It would not be possible to send complete logs but here are the logs added for states- 
[logs.txt](https://github.com/MyPureCloud/genesys-messenger-transport-mobile-sdk/files/11251473/logs.txt)

In these you can see the "Reconnecting" being logged many times.

One more observation - This starts happening after agent sends a message.

**Comment by AfanasievAnton** [comment]
You should have some Exceptions printed to the console during reconnection. can you show me how they look?

**Comment by androiddev1992** [comment]
These exceptions are being logged: 

`
java.lang.Throwable: Failed to reconnect.
                                                                                                    	at com.genesys.cloud.messenger.transport.network.PlatformSocket$openSocket$1.onFailure(PlatformSocket.kt:43)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket.writePingFrame$okhttp(RealWebSocket.kt:563)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket$initReaderAndWriter$lambda-3$$inlined$schedule$1.runOnce(TaskQueue.kt:219)
                                                                                                    	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
                                                                                                    	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
                                                                                                    	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:929)
                                                                                                    Caused by: java.net.SocketTimeoutException: sent ping but didn't receive pong within 15000ms (after 3 successful ping/pongs)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket.writePingFrame$okhttp(RealWebSocket.kt:563) 
                                                                                                    	at okhttp3.internal.ws.RealWebSocket$initReaderAndWriter$lambda-3$$inlined$schedule$1.runOnce(TaskQueue.kt:219) 
                                                                                                    	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116) 
                                                                                                    	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42) 
                                                                                                    	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:929) 
`


`java.lang.Throwable: Failed to reconnect.
                                                                                                    	at com.genesys.cloud.messenger.transport.network.PlatformSocket$openSocket$1.onFailure(PlatformSocket.kt:43)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
                                                                                                    	at okhttp3.internal.ws.RealWebSocket$connect$1.onFailure(RealWebSocket.kt:202)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:929)
                                                                                                    Caused by: java.io.IOException: unexpected end of stream on https://webmessaging.mypurecloud.de/...
                                                                                                    	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
                                                                                                    	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:457)
                                                                                                    	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262)
                                                                                                    	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:929) 
                                                                                                    Caused by: java.io.EOFException: \n not found: limit=0 content=…
                                                                                                    	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
                                                                                                    	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
                                                                                                    	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
                                                                                                    	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:457) 
                                                                                                    	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262) 
                                                                                                    	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) 
                                                                                                    	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) 
                                                                                                    	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) 
                                                                                                    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221) 
                                                                                                    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
                                                                                                    	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) 
                                                                                                    	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:929) `

Also, I did a ping test just to check with multiple servers and average was around 300ms.

**Comment by AfanasievAnton** [comment]
@androiddev1992 Another question: Are you able to reproduce this with our Testbed application?

**Comment by androiddev1992** [comment]
Same issue is happening with Testbed application. I have shared the logs over email. Please check

**Comment by AfanasievAnton** [comment]
Issue is not reproducible anymore.
